### ISSUE TITLE
Files not appearing on printer

### ISSUE THREAD

**Issue by tds2021** [gilesdavison/RadaDASH#1]
I have set up a Raspberry Pi Zero W as outlined in your instructions and connected it to my printer.  However, the wifi.txt never appeared for me to print it. I copied it to a regular USB and printed it.  that cleared my previous WiFi config.

On the system > Info panel, I briefly saw a message about DHCP, but now it just cycles between Link AP, please wait, and Link AP failed.  I do not get an IP address from the Pi Zero.

My printer is an AnyCubic Photon Mono X.

**Comment by gilesdavison** [comment]
With regards to the printer connection, unfortunately that is an AnyCubic issue and one I've experienced myself. Hopefully they'll fix it in a future firmware update. I would suggest rebooting or trying to connect it to a different wireless network, perhaps a phone hotspot. In my experience it seems to connect without issue about 80% of the time.

The WiFi.txt file (and any other files uploaded to the Pi) should show up even if the printer has not successfully connected to the WiFi. If the RadaDASH is appearing when you browse to the webpage then this is most likely an issue creating the g_mass_storage gadget. Simple things first, check that you are using the [usb port of the Pi and not the power side](https://www.electronics-lab.com/wp-content/uploads/2016/08/Raspberry-Pi-Zero-Ethernet-Gadget-Pi-Zero-Plugged-Into-Micro-USB-Port.jpg). 

If you are using the right port on the Pi then [connect to the Pi over SSH](https://www.raspberrypi.org/documentation/remote-access/ssh/unix.md) (login details: Pi/rada) and pastebin the result of `lsusb` and `dmesg`. You can also try connecting the Pi to your computer instead of the printer and see if a USB drive appears after a minute or two.

**Comment by gilesdavison** [comment]
With regards to the printer connection, unfortunately that is an AnyCubic issue and one I've experienced myself. Hopefully they'll fix it in a future firmware update. I would suggest rebooting or trying to connect it to a different wireless network, perhaps a phone hotspot. In my experience it seems to connect without issue about 80% of the time.

The WiFi.txt file (and any other files uploaded to the Pi) should show up even if the printer has not successfully connected to the WiFi. If the RadaDASH is appearing when you browse to the webpage then this is most likely an issue creating the g_mass_storage gadget. Simple things first, check that you are using the [usb port of the Pi and not the power side](https://www.electronics-lab.com/wp-content/uploads/2016/08/Raspberry-Pi-Zero-Ethernet-Gadget-Pi-Zero-Plugged-Into-Micro-USB-Port.jpg). 

If you are using the right port then connect to the Pi over SSH (login details: Pi/rada) and pastebin the result of `lsusb` and `dmesg`. You can also try connecting the Pi to your computer instead of the printer and see if a USB drive appears after a minute or two.

**Comment by tds2021** [comment]
I connected the Pi to my PC, to my PC, but it never appeared as a USB device.  The web GUI was accessible and I was able to reach it via SSH.

Here is the lsusb and message output.

https://pastebin.com/hwigGBYM

**Comment by TDS1969** [comment]
Also, I created a new CD card to make sure it was not an imaging issue.  In both cases, the Zero does not appear as a USB device on my Mac or my PC.  Is there something I can check from SSH on why it's not presenting as a USB storage device?

**Comment by gilesdavison** [comment]
The output of `dmesg` that you provided shows the usb gadget is being created correctly, but it does not show any connection with the host. To double-triple check as you didn't comment, you are using the [port labelled "USB"](https://www.electronics-lab.com/wp-content/uploads/2016/08/Raspberry-Pi-Zero-Ethernet-Gadget-Pi-Zero-Plugged-Into-Micro-USB-Port.jpg) on the Pi and **not** the port labelled "PWR IN", correct?

**Comment by TDS1969** [comment]
yes, I have confirmed that I am using the port marked USP on the board.  It's the one closest to the HDMI port.  I let it sit for 30 min while on a call.

**Comment by TDS1969** [comment]
The fifth try is the charm.  I recreated the SD card several more times.  On the last attempt, it appeared as a USB drive.  It's now communicating with the printer; hopefully it remains stable.

**Comment by tds2021** [comment]
One of the files I was trying to upload was really large and didn’t make it.  I decided to see about getting network access to the uploads directory as well as the web GUI.  Here are the steps I took to get SMB working.  I still need to do some testing of what happens when you upload this way, but so far it looks promising. You may want to consider this as part fo your standard build as well. It’s much faster than a web POST.



Troy Smith
troy@create-more.com

“There are two kinds of people in the world: Those who divide everybody into two kinds of people, and those who don’t.” — Robert Benchley, 1920


Adding network access to the upload directory

The next step is to provide network access to the upload folder.

sudo apt-get update
sudo apt-get install samba winbind -y

When the installation is complete, we need to configure a Samba network share. For simplicity, this will not require a user name or password, as it is already protected by your wireless network security. If you want more security, see wiki.samba.org.
sudo nano /etc/samba/smb.conf

Scroll down to the end of the file and append the lines below:

[usb]
browseable = yes
path = /home/pi/RadaDASH/upload
guest ok = yes
read only = no
create mask = 777

Press CTRL+O followed by Enter to save, and then CTRL+X to quit.

Now restart the Samba service for the changes to take effect:

sudo systemctl restart smbd.service

**Comment by gilesdavison** [comment]
Glad it's working, I'll take a deeper look into stabilising this for future releases. With regards to SMB [this](https://magpi.raspberrypi.org/articles/pi-zero-w-smart-usb-flash-drive) is actually what inspired RadaDASH. I thought about adding it but I would like to contain everything to the dashboard, mirroring OctoPrint and other 3D printer dashboards. Plus there is no reason why an SMB transfer should be faster than HTTP, but I'll looking into chunking the uploads to improve stability. I'll also definitely be adding some upload progress feedback.

**Comment by tds2021** [comment]
I was trying to get the solution you linked working as well.  I followed the steps and got the pi to mount on my Mac and a PC (with a few tweeks).  However, when I connect it to my printer the touch screen locks up and I can’t do anything.  This seems like the same issue you’re having in your solution.  If you find something to try, could you share it with me?  I’d like to the this working as well for a friend that has other printers.
