### ISSUE TITLE
On printer interface locks up

### ISSUE THREAD

**Issue by tds2021** [gilesdavison/RadaDASH#2]
After printing from the radadash interface, the on printer controls lock up.  You cannot switch back to the printer tools to raise the platform without first power cycling the printer. Additionally, after starting a print job, you cannot access the gear menu on the printer to just the base exposure on a file.  Finally, the radadash site loses its connection to the printer and cannot re-connect until after the printer is power cycled.

**Comment by gilesdavison** [comment]
This could be one of two scenarios, the usb gadget causing the Mono X to freeze on a connection cycle or some issue with the command handling on the printer, both of which I've had occur to me. As RadaDASH uses identical commands to the ANYCUBIC app this is something AC will need to fix. However the USB gadget occasionally causing printer freezes I will look into. Either way, if you're not already I would suggest upgrading to the 3.4.7 firmware on your Mono X, this helped significantly and I have not had any issues since.

**Comment by tds2021** [comment]
I am upgrade, but thank you for the suggestion

Troy Smith
troy@create-more.com

“There are two kinds of people in the world: Those who divide everybody into two kinds of people, and those who don’t.” — Robert Benchley, 1920

**Comment by tds2021** [comment]
I believe the issue is that the printer needs to be able to write to the USB device.  It creates the history file on the drive and uses it as its working space.  In your app.py file, change ro=1 to ro=0.  THat seemed to fix it for me.

**Comment by gilesdavison** [comment]
Great spot! You're right, this should definitely be `ro=0`, I'll update this in the release this week. Still unsure why this would cause intermittent problems, will look into it further.
